# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80e599f8e727802f5c403654d14845e82640b8cc2cad6b9c863fab4802ad9d0ea94a0df1d02b070ad8e85dad488ae3cf59ef693e9d41ad35fe2953f8b5b7b0d1

test:
  secret_key_base: ad2d586063b89c699eaa8b816ee4e198ba86390331ec94c0099267cd6bd5c29a086e2a26bb76de66c4a8449d536eac69862678c6647615ca399df3ecef2199dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
